#!/usr/bin/env python3
"""Week 3 to Week 4 handoff experiment.

The signal m(t) is a manually specified slow modulator. It is deliberately not
called a hormone. In Week 4, students replace this schedule with a hormone
concentration generated by stimulation, decay, and receptor dynamics.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

from cpg_walk_sim import LEGS, TRIPOD_SIGN, rising_crossings, step_cpg


DT = 0.05
ALPHA = 1.10
PHI_0 = 0.20
PHI_GAIN = 0.20
PHI_BOUNDS = (0.10, 0.45)
STRIDE_0 = 0.055
STRIDE_GAIN = 0.010
STRIDE_BOUNDS = (0.040, 0.070)
LIFT_HEIGHT = 0.030


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def manual_modulator(t: float) -> float:
    """0 for 10 s, 1 for 10 s, then 0 for 10 s."""
    return 1.0 if 10.0 <= t < 20.0 else 0.0


def mapped_parameters(m: float) -> tuple[float, float]:
    phi = clamp(PHI_0 + PHI_GAIN * m, *PHI_BOUNDS)
    stride = clamp(STRIDE_0 + STRIDE_GAIN * m, *STRIDE_BOUNDS)
    return phi, stride


def simulate(duration: float = 30.0, warmup: float = 10.0) -> list[dict]:
    o1, o2 = 0.10, 0.00
    for _ in range(round(warmup / DT)):
        o1, o2 = step_cpg(o1, o2, ALPHA, PHI_0)

    body_x = 0.0
    foot_world = {leg: 0.0 for leg in LEGS}
    was_contact = {leg: False for leg in LEGS}
    rows: list[dict] = []

    for k in range(round(duration / DT) + 1):
        t = k * DT
        m = manual_modulator(t)
        phi, stride = mapped_parameters(m)
        leg_state, constraints = {}, []
        for leg in LEGS:
            sign = TRIPOD_SIGN[leg]
            x_rel = stride * sign * o1
            lift = LIFT_HEIGHT * max(0.0, sign * o2)
            contact = sign * o2 <= 0.0
            leg_state[leg] = (x_rel, lift, contact)
            if contact and not was_contact[leg]:
                foot_world[leg] = body_x + x_rel
            if contact:
                constraints.append(foot_world[leg] - x_rel)
        if constraints:
            body_x = sum(constraints) / len(constraints)

        row = {
            "time_s": t, "modulator_m": m, "alpha": ALPHA,
            "phi_rad": phi, "stride_half_m": stride,
            "o1": o1, "o2": o2, "body_x_m": body_x,
            "support_legs": len(constraints),
        }
        for leg, (x_rel, lift, contact) in leg_state.items():
            if not contact:
                foot_world[leg] = body_x + x_rel
            row[f"{leg}_contact"] = int(contact)
            row[f"{leg}_lift_m"] = lift
            was_contact[leg] = contact
        rows.append(row)
        o1, o2 = step_cpg(o1, o2, ALPHA, phi)

    x0 = rows[0]["body_x_m"]
    for row in rows:
        row["body_x_m"] -= x0
    return rows


def segment_metrics(rows: list[dict], start: float, end: float) -> dict:
    segment = [r for r in rows if start <= r["time_s"] <= end]
    crossings = rising_crossings([r["o1"] for r in segment])
    periods = [(crossings[i] - crossings[i - 1]) * DT for i in range(1, len(crossings))]
    frequency = 1.0 / (sum(periods) / len(periods)) if periods else 0.0
    distance = segment[-1]["body_x_m"] - segment[0]["body_x_m"]
    return {
        "start_s": start, "end_s": end,
        "modulator_m": segment[len(segment) // 2]["modulator_m"],
        "phi_rad": segment[len(segment) // 2]["phi_rad"],
        "stride_half_m": segment[len(segment) // 2]["stride_half_m"],
        "distance_m": round(distance, 6),
        "mean_speed_m_s": round(distance / (end - start), 6),
        "frequency_hz": round(frequency, 6),
        "minimum_support_legs": min(r["support_legs"] for r in segment),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=Path("output/week4_bridge"))
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    rows = simulate()
    with (args.output_dir / "week4_bridge.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    segments = [segment_metrics(rows, a, b) for a, b in ((0, 10), (10, 20), (20, 30))]
    contract = {
        "purpose": "Week 3 output contract for Week 4",
        "slow_input": "manual modulator m(t); replace with hormone concentration in Week 4",
        "controlled_parameters": {
            "phi_rad": {"baseline": PHI_0, "gain": PHI_GAIN, "bounds": PHI_BOUNDS},
            "stride_half_m": {"baseline": STRIDE_0, "gain": STRIDE_GAIN, "bounds": STRIDE_BOUNDS},
        },
        "fixed_parameters": {"alpha": ALPHA, "dt_s": DT, "lift_height_m": LIFT_HEIGHT},
        "segments": segments,
        "claim_boundary": "manual bounded modulation only; no hormone dynamics are implemented",
    }
    (args.output_dir / "handoff_contract.json").write_text(
        json.dumps(contract, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(contract, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
